name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        xcode: ['Xcode_13.0', 'Xcode_12.4']
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: set -o pipefail && make build | xcpretty
    - name: Run tests
      run: make test
