name: CI

on:
  push:
    branches: [ main, matrixBuild ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-11
    strategy:
      matrix:
        xcode: [Xcode_12.4, Xcode_12.5, Xcode_13.0] # swift-tools-version 5.3, 5.4, 5.5
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Run tests
      run: make test
